# =================================================
# === 팀 공통 데이터셋 및 모델 설정 파일 ===
# =================================================
# 이 파일의 경로나 변수명은 모든 팀원이 동일하게 유지해야 합니다.

# 1. 데이터셋 경로 설정
# 이 YAML 파일이 있는 위치(프로젝트 루트)를 기준으로 상대 경로를 지정합니다.
path: ./01_data  # 데이터셋의 상위 폴더
train: train/images
val: valid/images
test: test/images

# 2. 클래스 정보
nc: 1  # 클래스 개수 (사과 하나이므로 1)
names: ['apple'] # 클래스 이름 리스트

# 3. 모델 학습 하이퍼파라미터 (팀 공통 합의 사항)
# 이 값을 기준으로 각자 모델을 학습합니다.
epochs: 100
batch_size: 16
imgsz: 640 # 입력 이미지 크기
learning_rate: 0.01
patience: 20 # 조기 종료(Early Stopping)를 위한 설정. 20 epoch 동안 검증 성능 향상이 없으면 학습 중단.

